"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MenuOption = exports.ToppingAmountButton = exports.AddMoreToppingsButton = exports.SummaryText = exports.SummaryTitle = exports.OrderSummary = exports.ToppingLabel = exports.Checkbox = exports.ToppingItem = exports.ToppingsContainer = exports.Select = exports.Label = exports.FormSection = exports.Title = exports.FormContainer = void 0;
var styled_components_1 = require("styled-components");
exports.FormContainer = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  max-width: 500px;\n  margin: 0 auto;\n  padding: 2rem;\n  background-color: white;\n  border-radius: 8px;\n  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n"], ["\n  max-width: 500px;\n  margin: 0 auto;\n  padding: 2rem;\n  background-color: white;\n  border-radius: 8px;\n  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n"])));
exports.Title = styled_components_1.default.h2(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  font-size: 1.7rem;\n  font-weight: bold;\n  color: #1a1a1a;\n  margin-bottom: 1.5rem;\n"], ["\n  font-size: 1.7rem;\n  font-weight: bold;\n  color: #1a1a1a;\n  margin-bottom: 1.5rem;\n"])));
exports.FormSection = styled_components_1.default.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  margin-bottom: 1.5rem;\n"], ["\n  margin-bottom: 1.5rem;\n"])));
exports.Label = styled_components_1.default.label(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  display: block;\n  font-size: 0.879rem;\n  font-weight: 500;\n  color: #4a5568;\n  margin-bottom: 0.5rem;\n  font-family: \"Josefin Sans\", serif;\n"], ["\n  display: block;\n  font-size: 0.879rem;\n  font-weight: 500;\n  color: #4a5568;\n  margin-bottom: 0.5rem;\n  font-family: \"Josefin Sans\", serif;\n"])));
exports.Select = styled_components_1.default.select(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  width: 100%;\n  padding: 0.5rem;\n  border: 1px solid #e2e8f0;\n  border-radius: 0.375rem;\n  background-color: white;\n  font-size: 1rem;\n  color: #4a5568;\n  cursor: pointer;\n\n&:focus {\n  outline: none;\n  border-color: #3182ce;\n  box-shadow: 0 0 0 3px rgba(49, 130, 206, 0.1);\n}\n"], ["\n  width: 100%;\n  padding: 0.5rem;\n  border: 1px solid #e2e8f0;\n  border-radius: 0.375rem;\n  background-color: white;\n  font-size: 1rem;\n  color: #4a5568;\n  cursor: pointer;\n\n&:focus {\n  outline: none;\n  border-color: #3182ce;\n  box-shadow: 0 0 0 3px rgba(49, 130, 206, 0.1);\n}\n"])));
exports.ToppingsContainer = styled_components_1.default.div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  gap: 0.5rem;\n  margin-bottom: 1.5rem;\n"], ["\n  display: flex;\n  flex-direction: column;\n  gap: 0.5rem;\n  margin-bottom: 1.5rem;\n"])));
exports.ToppingItem = styled_components_1.default.div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  gap: 0.5rem;\n  font-family: \"Josefin Sans\", serif;\n"], ["\n  display: flex;\n  align-items: center;\n  gap: 0.5rem;\n  font-family: \"Josefin Sans\", serif;\n"])));
exports.Checkbox = styled_components_1.default.input(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  width: 1rem;\n  height: 1rem;\n  cursor: pointer;\n  accent-color: #3182ce;\n"], ["\n  width: 1rem;\n  height: 1rem;\n  cursor: pointer;\n  accent-color: #3182ce;\n"])));
exports.ToppingLabel = styled_components_1.default.label(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  font-size: 0.879rem;\n  color: #4a5568;\n  cursor: pointer;\n  text-transform: capitalize;\n  margin-left: 10px;\n"], ["\n  font-size: 0.879rem;\n  color: #4a5568;\n  cursor: pointer;\n  text-transform: capitalize;\n  margin-left: 10px;\n"])));
exports.OrderSummary = styled_components_1.default.div(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\nbackground-color: #f7fafc;\npadding: 1rem;\nborder-radius: 0.375rem;\nmargin-bottom: 1.5rem;\n"], ["\nbackground-color: #f7fafc;\npadding: 1rem;\nborder-radius: 0.375rem;\nmargin-bottom: 1.5rem;\n"])));
exports.SummaryTitle = styled_components_1.default.h3(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n  font-size: 1rem;\n  font-weight: 500;\n  color: #4a5568;\n  margin-bottom: 0.5rem;\n"], ["\n  font-size: 1rem;\n  font-weight: 500;\n  color: #4a5568;\n  margin-bottom: 0.5rem;\n"])));
exports.SummaryText = styled_components_1.default.p(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n  color: #4a5568;\n  margin: 0.25rem 0;\n"], ["\n  color: #4a5568;\n  margin: 0.25rem 0;\n"])));
exports.AddMoreToppingsButton = styled_components_1.default.button(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n    width: 33%;\n    padding: 0.50rem;\n    border: 1px solid #ccc;\n    font-family: inherit;\n    border-radius: 0.375rem;\n  \n\n  &:hover {\n    background-color: #e2e1e1;\n  }\n\n  &:focus {\n    box-shadow: 0 0 0 3px rgba(49, 130, 206, 0.5);\n  }\n"], ["\n    width: 33%;\n    padding: 0.50rem;\n    border: 1px solid #ccc;\n    font-family: inherit;\n    border-radius: 0.375rem;\n  \n\n  &:hover {\n    background-color: #e2e1e1;\n  }\n\n  &:focus {\n    box-shadow: 0 0 0 3px rgba(49, 130, 206, 0.5);\n  }\n"])));
exports.ToppingAmountButton = styled_components_1.default.button(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n  background-color: ", ";\n  color: white;\n  border: none;\n  padding: 5px 10px;\n  margin: 0 2px;\n  border-radius: 4px;\n  cursor: pointer;\n  transition: background-color 0.3s ease;\n  \n  &:hover {\n    background-color: ", ";\n  }\n"], ["\n  background-color: ", ";\n  color: white;\n  border: none;\n  padding: 5px 10px;\n  margin: 0 2px;\n  border-radius: 4px;\n  cursor: pointer;\n  transition: background-color 0.3s ease;\n  \n  &:hover {\n    background-color: ", ";\n  }\n"])), function (props) { return props.selected ? '#4a4a4a' : '#6a6a6a'; }, function (props) { return props.selected ? '#5a5a5a' : '#7a7a7a'; });
exports.MenuOption = styled_components_1.default.option(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n  text-transform: capitalize;\n"], ["\n  text-transform: capitalize;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15;
